apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: SunBha
        repo: gitops-preview-env
        tokenRef:
          secretName: argocd-token
          key: token
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'preview-env-{{.number}}'
    spec:
      source:
        repoURL: 'https://github.com/SunBha/gitops-preview-env.git'
        targetRevision: '{{.head_sha}}'
        path: kustomize-preview-app/ 
        kustomize:
          images:
            - 'docker.io/bhatiasunny/my-preview-app:{{.head_short_sha_7}}'
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-pr-{{.number}}'
      syncPolicy:
        automated:
          prune: true  
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
